### ISSUE TITLE
Zenekar létrehozása felület

### ISSUE THREAD

**Issue by kuglert** [progmatic-java-2022/spoti-live#24]
- [x] telefonszam modositas nem mukodik
- [x] ha mar letezo nevre modositunk normalis hibauzenet jojjon
- [x] ha mar letezo emailre modositunk normalis hibauzenet jojjon
- [x] ha mar letezo telefonszamra modositunk normalis hibauzenet jojjon
- [x] ha ugyanolyan telefonszamu zenekart adunk hozza emailes a hobauzenet

**Comment by Laszlotamas997** [comment]
- [ ]
